### ISSUE TITLE
Log level

### ISSUE THREAD

**Issue by maxogden** [sindresorhus/electron-debug#1]
not sure exactly what can be done here yet, but maybe supressing logs unless `process.env.DEBUG` has either `electron` or `*` in it maybe? the electron log level APIs are kinda weird, would be nice to abstract them sanely

**Comment by sindresorhus** [comment]
Is this still relevant? I don't see any Electron logging by default.

**Comment by parro-it** [comment]
They made chromium logging to console an opt-in some release ago. You can use the [--enable-logging](https://github.com/electron/electron/blob/master/docs/api/chrome-command-line-switches.md#--enable-logging) argument to restore the logging.

I think you can safely close this.
