### ISSUE TITLE
Different require in webContents throws blocks loading right click context

### ISSUE THREAD

**Issue by mariokostelac** [sindresorhus/electron-debug#13]
If Ember app is wrapped in Electron, original `module` and `require` globals have to be replaced with ember versions of that.
That blocks loading right click context on https://github.com/sindresorhus/electron-debug/blob/master/index.js#L25.
Could we make `require` call configurable?

**Comment by sindresorhus** [comment]
Configurable how? I would strongly prefer a workaround that doesn't introduce configuration.

**Comment by mariokostelac** [comment]
I was thinking something like 
```
webContents.executeJavaScript(`${settings.require_fn}('${__dirname}/context-menu').install();`);
```
having `settings.require_fn` set to `'require'` by default.

**Comment by parro-it** [comment]
I think `browser-window-created` app event is called before user get any change to load an url on the browser window instance. 
The event receive the browser window instance as an argument. We could use this event to save original value of `require` and than use that to load the context-menu module.

This way no configuration is needed at all, and user code on page could do wehatever it want to `window.require`. I could prepare a PR for this.

**Comment by sindresorhus** [comment]
:+1:

**Comment by mariokostelac** [comment]
@parro-it would you create a PR for that or you want me to do that?

**Comment by parro-it** [comment]
@mariokostelac I will, thank you.
