### ISSUE TITLE
Should we handle shortcut consistently with Chrome?

### ISSUE THREAD

**Issue by parro-it** [sindresorhus/electron-debug#16]
See [this issue on electron repo](https://github.com/atom/electron/issues/3345)

**Comment by sindresorhus** [comment]
Let's see what happens with that issue first.

**Comment by parro-it** [comment]
:+1:

**Comment by sindresorhus** [comment]
@parro-it What should we do about this?

**Comment by parro-it** [comment]
There seems to be no interest in the feature, I think we can close it.
Rethinking about this issue year after, I can't remember why I felt we should use the same shortcuts as Chrome.
