### ISSUE TITLE
Debug IPC

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/electron-debug#25]
Could maybe be useful to monkey-patch the [IPC module](http://electron.atom.io/docs/latest/api/ipc-main/) and log what's sent through it.

-

Vote with reactions whether you want this or not.

**Comment by parro-it** [comment]
It would be useful, but I fear it will bloat the console (Are you thinking to logging to console?)
Ideallly, we need a way to turn logging on/off from devtools.

**Comment by sindresorhus** [comment]
@parro-it In the DevTools console you can filter based on the log type. We could log using `console.debug` in this case. It should also be an option you turn on.

**Comment by parro-it** [comment]
Yes, it should be fine...

**Comment by parro-it** [comment]
This appear to be implemented in [devtron](https://github.com/electron/devtron). 
Did you already check it?

**Comment by sindresorhus** [comment]
Yes, Devtron does this well.

**Comment by NoahAndrews** [comment]
Devtron is no longer maintained, and seems to be broken with modern electron versions, so it might be a good idea to revisit this.
