### ISSUE TITLE
electron-debug module not found when running packaged app

### ISSUE THREAD

**Issue by Kamahl19** [sindresorhus/electron-debug#26]
Hi,

when I run electron app using electron-prebuild, it works ok with electron-debug.

However when I pack app using electron-packager and then run those packaged apps, I get electron-debug module not found error. 
![error](https://cloud.githubusercontent.com/assets/1591293/11398748/15b94cf0-9383-11e5-8e95-7663e74dbc83.PNG)

**Comment by sindresorhus** [comment]
You have to make sure you include the node_modules folder in your packaged app.
