### ISSUE TITLE
Coffeescript inside index.js

### ISSUE THREAD

**Issue by lyckade** [sindresorhus/electron-debug#27]
The code inside the index.js file causes error, because it is not valid JavaScript. The syntax looks like not compiled coffeescript:

    module.exports = opts => {
	opts = opts || {};

	app.on('browser-window-created', (e, win) => {
		if (opts.showDevTools) {
			devTools(win);
		}
	});

	app.on('ready', () => {
		localShortcut.register(isOSX ? 'Cmd+Alt+I' : 'Ctrl+Shift+I', devTools);
		localShortcut.register('F12', devTools);

		localShortcut.register('CmdOrCtrl+R', refresh);
		localShortcut.register('F5', refresh);
	});
    };

**Comment by parro-it** [comment]
You have to use this module with [Electron](http://electron.atom.io/)

**Comment by lyckade** [comment]
> You have to use this module with Electron

The issue is that coffeescript syntax is used inside a JavaScript file. When you try to install this module via npm you will get an error. 

Even if you have electron installed there is an error, because it is not JavaScript.

**Comment by sindresorhus** [comment]
It's *JavaScript* [arrow functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions). Upgrade to the latest version of Electron.

**Comment by Qix-** [comment]
First hint should have been that there are no brackets in Coffeescript other than for object initializers...

**Comment by lyckade** [comment]
O.k. my mistake. It is valid ES6. And I know that it is not valid coffeescript either. 

The problem was that the yeoman boilerplate was not working any more for new projects, because the npm install didn't work any more. The error was allways at the fat arrows. After a first watch I thought somebody mixed here some coffeescript elements into JS.
Now I know.
At the moment the yeoman boilerplate also don't work cause of this ES6 syntax. Even after an update of my global electron the boilerplate is not working. I am checking now the boilerplate.
