### ISSUE TITLE
Option to start in detached dock mode

### ISSUE THREAD

**Issue by stevedekorte** [sindresorhus/electron-debug#29]
It would be nice to have an option for the debugger window mode. Something like "dockSide" with options of "detached", "bottom", or "right" and a default of "right".

require('electron-debug')({
	showDevTools: true,
        dockSide: "detached",
});

Btw, I've found the electron-debug package extremely useful. Thanks for making it!

**Comment by sindresorhus** [comment]
`detached` could be implemented, but the rest is not supported by Electron: http://electron.atom.io/docs/v0.36.7/api/web-contents/#webcontentsopendevtoolsoptions Can you open an issue on Electron about that?

I think it should just reuse the existing option as `showDevTools: 'detached'`.

Wanna do a pull request?

**Comment by parro-it** [comment]
@sindresorhus, I think the other options could be implemented too.
Using [webContents.devToolsWebContents](http://electron.atom.io/docs/v0.36.7/api/web-contents/#webcontentsdevtoolswebcontents) we can get the `webContents` of `devtools`, and then using [BrowserWindow.fromWebContents(webContents)](http://electron.atom.io/docs/v0.36.7/api/browser-window/#browserwindowfromwebcontentswebcontents) we can retrieve its `BrowserWindow` instance.
Once we have it, we can move and size it wherever we want.
It probably isn't a simple thing to implement :cry:

**Comment by sindresorhus** [comment]
@parro-it Yes, but Chrome Dev Tools already have ability to dock to right or bottom, so I think this should be implemented in Electron.

**Comment by parro-it** [comment]
Uhm, yes, you're right...

**Comment by sindresorhus** [comment]
@parro-it Would you mind opening an Electron issue so this can be eventually resolved?

**Comment by parro-it** [comment]
Done: https://github.com/electron/electron/issues/5094

**Comment by sindresorhus** [comment]
@parro-it Thank you :)

**Comment by parro-it** [comment]
:wink:

**Comment by sindresorhus** [comment]
The feature is now available in Electron 0.37.7 if anyone wants to do a PR:

> Add mode option to webContents.openDevTools(options) API.

https://github.com/electron/electron/releases/tag/v0.37.7

**Comment by stevedekorte** [comment]
Thanks!

**Comment by sindresorhus** [comment]
Fixed by #35.
