### ISSUE TITLE
Expose core action functions to call them from debug-menu

### ISSUE THREAD

**Issue by parro-it** [sindresorhus/electron-debug#30]
I'm thinking about adding a feature to debug-menu that allow to add a "Debug" menu to a BrowserWindow instance. I'm describing my idea in parro-it/debug-menu#3 there.

I want to call `electron-debug` `devTools` and `refresh` methods from my `debug-menu` module, to avoid reimplementing them. They will be called from the corresponding MenuItem of this new "Debug" menu.

I will write a PR that expose them in the API of `electron-debug` if you think it's a good idea...

**Comment by sindresorhus** [comment]
How would that API look like? There's not a lot of code in this module.

**Comment by parro-it** [comment]
I will add `devTools` and `refresh` function as properties of currently exported function.
`refresh` function could also be improved to take a BrowserWindow instance as a argument like `devTools` does (this should not break compatibility with previoud versions).

Yes, both functions are very simple and I could easily reimplement them, but I think it will be better to reuse them. What do you think about?

**Comment by sindresorhus** [comment]
:+1:
