### ISSUE TITLE
Uglify failed

### ISSUE THREAD

**Issue by callmewhy** [sindresorhus/electron-debug#39]
Hi, I'm using `electron-debug` in webpack.

However, there is an error with UglifyJsPlugin:
```
new webpack.optimize.UglifyJsPlugin({
      compress: {
        warnings: false,
      },
    }),
```

That is because UglifyJs doesn't support ES6 and the project code is written without transpiler (like babel).

**Comment by sindresorhus** [comment]
You shouldn't Webpack the Electron code.
