### ISSUE TITLE
More shortcuts

### ISSUE THREAD

**Issue by Flet** [sindresorhus/electron-debug#4]
Thanks for creating this little helper package, its quite useful!

Is there any interest in adding more shortcuts for refresh and dev tools? Some folks may be accustomed to the other shortcut keys in Chrome.

Refresh: <kbd>F5</kbd>
Dev Tools:<kbd>F12</kbd>

Happy to make a PR if this matches your vision.

**Comment by sindresorhus** [comment]
:+1:
