### ISSUE TITLE
How to open DevTools undocked 'only' when CTRL+SHIFT+I & not on start?

### ISSUE THREAD

**Issue by bhaveshgohel** [sindresorhus/electron-debug#42]

**Comment by kevva** [comment]
https://github.com/sindresorhus/electron-debug#showdevtools

**Comment by bhaveshgohel** [comment]
Thanks @kevva, I figure It out :

```javascript
require('electron-debug')({enabled:false, showDevTools: 'undocked'});
```

One small Caveat:
Why its says "(last dock state)" in readme? Can we force it to be always the same we configured?
Asking because after the above configuration i'm getting undocked Devtools with Ctrl+Shift+I, even after doing configuring as below .

```javascript
require('electron-debug')({enabled:false, showDevTools: 'right'});
```
```javascript
require('electron-debug')({enabled:false, showDevTools: 'bottom'});
```
```javascript
require('electron-debug')({enabled:false, showDevTools: 'false'});
```

How do i test:
1. Configure
2. Run App
3. press Ctrl+Shift+I
4. Close the app without changing Dock side
5. Repeat
