### ISSUE TITLE
Enable the element inspector with a keyboard shortcut

### ISSUE THREAD

**Issue by zeke** [sindresorhus/electron-debug#43]
Following up on https://github.com/electron/electron/issues/7147

In MacOS Chrome, hitting <kbd>Cmd</kbd><kbd>Shift</kbd><kbd>C</kbd> or <kbd>Cmd</kbd><kbd>Alt</kbd><kbd>c</kbd> enables [inspect element mode](https://developers.google.com/web/tools/chrome-devtools/iterate/inspect-styles/shortcuts?hl=en#accessing-devtools):

![screen shot 2016-09-08 at 10 22 28 pm](https://cloud.githubusercontent.com/assets/2289/18376321/04fb1146-7613-11e6-89e6-8df1c6e64037.png)

This doesn't work in Electron, though. You have to open devtools and click the little cursor icon. The following has been suggested as a way to implement it:

``` js
mainWindow.webContents.on('devtools-opened', function () {
  mainWindow.devToolsWebContents.executeJavaScript('DevToolsAPI.enterInspectElementMode()')
})
```

**Comment by sindresorhus** [comment]
Good idea! Pull request welcome, as I'm busy IRL. Otherwise I'll get to it eventually.

**Comment by manojVivek** [comment]
@zeke @sindresorhus Any idea on how to make the same work for a `<webview />` devTools? 

`webview.devToolsWebContents` is always `null`.
