### ISSUE TITLE
Cannot open devtools in `electron-packager`-packaged app

### ISSUE THREAD

**Issue by ericsoco** [sindresorhus/electron-debug#46]
I have the `enabled: true` option set, as it's not a security concern for my use case:
```
require('electron-debug')({
	enabled: true
});
```

But when packaged with [`electron-packager'](https://github.com/electron-userland/electron-packager), the keyboard shortcuts fail to work and application menus are all gone.

Not clear where the issue lies, here or `electron-packager`; looking through the source here, it seems that the keyboard shortcuts should be active.

**Comment by sindresorhus** [comment]
Probably a problem with your code somehow. I'm using exactly this in [Caprine](https://github.com/sindresorhus/caprine/blob/35876fd223ea2494473b58510e3e46b03ba7d650/index.js#L11) and it's working fine.

**Comment by ericsoco** [comment]
Not sure why `electron-debug` menus aren't appearing, but [this comment](https://github.com/electron-userland/electron-packager/issues/553#issuecomment-270805213) helped me understand that the [`default_app`](https://github.com/electron/electron/tree/master/default_app) is launched when running from the commandline, but a vanilla app with no menus is run when packaged. I added menu items manually to my electron entry point and am good to go.
