### ISSUE TITLE
Option to not focus devtools windows

### ISSUE THREAD

**Issue by develar** [sindresorhus/electron-debug#53]
Currently, if devtools window undocked, it is focused and it is not convenient. electron-debug should [unfocus](https://github.com/electron/electron/issues/4764#issuecomment-196263172) by default, or at least, provide an option to unfocus.

**Comment by sindresorhus** [comment]
I think devtools should be unfocused when opened with the `showDevTools` option, but focused if you press the keyboard shortcuts. Don't think an option is needed.

**Comment by sindresorhus** [comment]
Fixed by https://github.com/sindresorhus/electron-debug/commit/2bbe00e8d165656da216cebbb2ea3544d67da628

Also vote up this Electron issue: https://github.com/electron/electron/issues/13095
