### ISSUE TITLE
insp is not a function

### ISSUE THREAD

**Issue by yangwao** [sindresorhus/electron-debug#54]
I recently updated to electron-debug@1.4.0, when I close inspector and I click anywhere/press alt/cmd/ctrl/random key or I'll try reopen inspector again, I shows me this window 
![image](https://user-images.githubusercontent.com/5887929/29005044-52790a48-7ad3-11e7-9e99-393b9f015a10.png)
Downgrade to electron-debug@1.3.0 helped me.
Officially reported by me https://github.com/SimulatedGREG/electron-vue/issues/342

**Comment by sindresorhus** [comment]
// @parro-it

**Comment by parro-it** [comment]
I removed my dependency on insp as a workaround.
Could you retry and check if it solve your issue? 
You should have electron-localshortcut version 3.0.2 installed.

**Comment by parro-it** [comment]
@yangwao should be solved now, could you please remove node_modules folder and retry?

**Comment by yangwao** [comment]
Fixed! Thanks! 🤗
Worked with these
```
⫸  npm ls --depth 0
my-electron@0.0.0 /Users/wao/Lab/my-electron
├── axios@0.16.2
├── babel-core@6.25.0
├── babel-loader@7.1.1
├── babel-plugin-transform-runtime@6.23.0
├── babel-preset-env@1.6.0
├── babel-preset-stage-0@6.24.1
├── babel-register@6.24.1
├── babili-webpack-plugin@0.1.2
├── cfonts@1.1.3
├── chalk@1.1.3
├── copy-webpack-plugin@4.0.1
├── cross-env@5.0.4
├── css-loader@0.28.4
├── del@2.2.2
├── devtron@1.4.0
├── electron@1.7.5
├── electron-builder@19.19.1
├── electron-debug@1.4.0
├── electron-devtools-installer@2.2.0
├── extract-text-webpack-plugin@2.1.2
├── file-loader@0.11.2
├── html-webpack-plugin@2.30.1
├── json-loader@0.5.7
├── multispinner@0.2.1
├── style-loader@0.18.2
├── url-loader@0.5.9
├── vue@2.4.2
├── vue-electron@1.0.6
├── vue-html-loader@1.2.4
├── vue-loader@12.2.2
├── vue-router@2.7.0
├── vue-style-loader@3.0.1
├── vue-template-compiler@2.4.2
├── vuex@2.3.1
├── webpack@2.7.0
├── webpack-dev-server@2.6.1
└── webpack-hot-middleware@2.18.2
```

**Comment by parro-it** [comment]
You're welcome!
