### ISSUE TITLE
Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by motin** [sindresorhus/electron-debug#61]
[Webpack doesn't like](https://github.com/webpack/webpack/issues/196) them dynamic requires that electron-debug contains:

```
  WARNING in ./node_modules/electron-debug/index.js
  84:85-106 Critical dependency: the request of a dependency is an expression
   @ ./node_modules/electron-debug/index.js
```

Any chance they can be rewritten in a way that does not yield this warning when compiling with webpack?

**Comment by sindresorhus** [comment]
No, this should be fixed in Webpack.

**Comment by sindresorhus** [comment]
@sokra @TheLarkInn This is the gadzillion issue I've had to deal with about this warning. Please reopen https://github.com/webpack/webpack/issues/196 and lets find a solution for this.
