### ISSUE TITLE
electron-debug WARNING 

### ISSUE THREAD

**Issue by xcsweb** [sindresorhus/electron-debug#62]
WARNING in ./node_modules/electron-debug/index.js
  81:45-58 Critical dependency: the request of a dependency is an expression
   @ ./node_modules/electron-debug/index.js
   @ ./src/main/index.dev.js
   @ multi ./src/main/index.dev.js ./src/main/index.js

  WARNING in ./node_modules/electron-debug/index.js
  84:85-106 Critical dependency: the request of a dependency is an expression
   @ ./node_modules/electron-debug/index.js
   @ ./src/main/index.dev.js
   @ multi ./src/main/index.dev.js ./src/main/index.js

**Comment by sindresorhus** [comment]
This is just Webpack awfulness. Please show your frustration on the webpack issue tracker: https://github.com/webpack/webpack/issues/196
