### ISSUE TITLE
Electron refresh doesn't work for angular 5 dev build

### ISSUE THREAD

**Issue by amanganiello90** [sindresorhus/electron-debug#65]
Hi,
I have problems to refresh page in electron with F5 or Ctrl-R shortcut.
I load in my electron main package the angular 5 dev build under dist folder:

-----
function createWindow() {
  mainWindow = new BrowserWindow({
    autoHideMenuBar: true,
    width: 640,
    height: 480,
	webPreferences: {
	nodeIntegration: false   }
  });
  mainWindow.loadURL(`file://${__dirname}/dist/index.html`);
  //mainWindow.webContents.openDevTools();
  mainWindow.on("closed", function() {
    mainWindow = null;
  });
}
-----
On refresh page I have the error "net::ERR_FILE_NOT_FOUND" for resources located under dist.

The command doesn't break for **Angular 5 PROD build**, but I need the feature also in dev build.

**Comment by sindresorhus** [comment]
This has nothing to do with `electron-debug`. It just reloads the window. You would get the same error with `window.location.reload()` too.
