### ISSUE TITLE
Use local shortcuts

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/electron-debug#8]
Instead of the [subscribe/unsubscribe](https://github.com/sindresorhus/electron-debug/blob/e5ae265a958b71d2a544ab3b0d093ff50e2b8d87/index.js#L26-L38) mess.

Depends on https://github.com/atom/electron/issues/1334.

**Comment by parro-it** [comment]
I think this could be closed now that we use [electron-localshortcut](https://github.com/parro-it/electron-localshortcut)?

**Comment by sindresorhus** [comment]
@parro-it Keeping it open as I still have a hope it will be in Electron core.

**Comment by parro-it** [comment]
:+1:
