### ISSUE TITLE
require waring 

### ISSUE THREAD

**Issue by liudianwei** [sindresorhus/electron-debug#83]
there is a warning like this:
`WARNING in ./node_modules/electron-debug/index.js 108:45-58
  Critical dependency: the request of a dependency is an expression
   @ ./src/main/index.dev.js
   @ multi ./src/main/index.dev.js ./src/main/index.js

  WARNING in ./node_modules/electron-debug/index.js 109:61-74
  Critical dependency: the request of a dependency is an expression
   @ ./src/main/index.dev.js
   @ multi ./src/main/index.dev.js ./src/main/index.js`

It is because of this
`addExtensionIfInstalled('devtron', name => require(name).path);
addExtensionIfInstalled('electron-react-devtools', name => require(name).path);`

could we change the 'name' to a const value? Suggest author to change it. Thanks First

**Comment by sindresorhus** [comment]
This is a problem with Webpack. I would recommend opening an issue over at https://github.com/webpack/webpack/issues instead.
