### ISSUE TITLE
Fire event before opening dev tools

### ISSUE THREAD

**Issue by fishbone1** [sindresorhus/electron-debug#84]
Can you provide an event before the dev tools are opened? Ideally this event allows me aborting the action.

Use case: Show a confirmation or password window to prevent users from accidentally opening debug tools.

But I have an even more complex use case, which is why I actually ask for it:
We provide source maps which allow debugging production code in beta-phase. Those source maps are protected via HTTP authentication. Electron will show an "unknown error" when trying to load those source maps if auth is required. Unfortunately you cannot control, when the source maps are loaded, but I observed that they are loaded shortly after you open the dev tools. However, I mangaged to solve this, by sending an AJAX request (where authentication works as expected) BEFORE loading the source maps. So my goal is:

1. user presses F12
2. catch new 'before-show-dev-tools'-event and send AJAX request to server containing resource map
3. AJAX response has status 401 => app asks for authentication credentials
4. AJAX request is fired again with response 200
5. dev tools appear
6. dev tools will automatically load

**Comment by sindresorhus** [comment]
If Elecron provides such an event, you can just listen to it yourself. If Electron doesn't, there's not much `electron-debug` can do about it, and you should rather open this issue on the Electron issue tracker.
