### ISSUE TITLE
Adding this library removed Jest from packages

### ISSUE THREAD

**Issue by nholder06** [sindresorhus/electron-debug#86]
Hi! I am working on a project using electron, rx, and jest.  When installing your library, it removed Jest from our packages.  Running an npm install after added it back.  I am on a windows machine, a co-worker installed your library and had the same experience.  Not sure if this was intended, but wanted to bring it up.

**Comment by sindresorhus** [comment]
This should be opened at https://github.com/npm/cli. This package has nothing to do with the actual install process.
