### ISSUE TITLE
shortcuts dont work

### ISSUE THREAD

**Issue by shaderbytes** [sindresorhus/electron-debug#87]
npm installed

Example code used , firstly it opened a menu .. which i dont want. If I wanted that I could just bloody use `mainWindow.webContents.openDevTools();`

Which I did have and shortcuts did not work to close it. So googled around and found this. Hooray I thought my problems are solved. And now i find its useless. No shortcut keys work and I cant just start the app with no dev tools showing and use short keys to open it if I want. 

Oh well.. thanks for trying.

**Comment by sindresorhus** [comment]
Shortcuts work for me in the included example app. I cannot really do anything based on the little information provided here.
