### ISSUE TITLE
Add inspectElement on right click, like on chrome

### ISSUE THREAD

**Issue by parro-it** [sindresorhus/electron-debug#9]
Hi, I think it could be useful to add this feature to electron-debug.
I take the idea [from this question on SO](http://stackoverflow.com/questions/32636750/how-to-add-a-right-click-menu-in-electron-that-has-inspect-element-option-like)

If you think it will be usefule, I can prepare a PR, otherwise, I just add it on my app :-(

**Comment by parro-it** [comment]
I think it could be activated only when dev-tools is opened, to avoid conflicts with application behaviour

**Comment by sindresorhus** [comment]
Yeah, that's a good idea. Should only be added when devtools is open. PR would be welcome :)
