### ISSUE TITLE
Filter windows to apply debug tools

### ISSUE THREAD

**Issue by danikaze** [sindresorhus/electron-debug#90]
Consider the use case where the electron app does consist of more than one window, but we don't want to apply the debug utilities (or just some of them) to every window.

i.e. main window + debug utility window, etc.

My proposal would be to pass a `filter(window: BrowserWindow) => boolean | Options)` so it's executed in the `'browser-window-created'` event.

If the filter is not passed in the `debug(options)`, then add nothing new.
If passed and it returns
- true: do nothing new, apply the passed options
- false: do not apply debug tools
- object (`Options`): apply the new options.

This would allow to say like: "apply debug utilities to my windows, but not the utility one", or similar.

```ts
debug({
  filter: (win) => win.title == 'Debug help' ? { showDevTools: false } : true,
})
```

**Comment by sindresorhus** [comment]
Sounds good. I would name it `windowSelector`.

**Comment by danikaze** [comment]
Took a while to find some free time, but a PR is opened ;)
